### ISSUE TITLE
admin-chart with django 5

### ISSUE THREAD

**Issue by koukou777** [PetrDlouhy/django-admin-charts#71]
Request Method: | GET http://127.0.0.1:8000/admin/admin_tools_stats/dashboardstats/add/
raises the folling error message
Model instances passed to related filters must be saved.
What is the posssible solution?

**Comment by PetrDlouhy** [comment]
@koukou777 Could you please include screenshot and/or full stacktrace?

**Comment by theusontech** [comment]
![Imagem do WhatsApp de 2024-03-09 à(s) 11 53 46_4e338edc](https://github.com/PetrDlouhy/django-admin-charts/assets/143137475/6c55233e-8674-4800-a7a8-99cf2c32ee93)

[09/Mar/2024 11:53:27] "GET /admin/admin_tools_stats/dashboardstats/add/ HTTP/1.1" 500 181432
[09/Mar/2024 11:53:31] "GET /admin/ HTTP/1.1" 200 8078
[09/Mar/2024 11:53:32] "GET /admin/admin_tools_stats/dashboardstatscriteria/add/ HTTP/1.1" 200 13845
[09/Mar/2024 11:53:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[09/Mar/2024 11:53:35] "GET /admin/ HTTP/1.1" 200 8078
Internal Server Error: /admin/admin_tools_stats/dashboardstats/add/
Traceback (most recent call last):
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\admin_tools_stats\app_label_renamer.py", line 58, in wrap
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\contrib\admin\options.py", line 1871, in _changeform_view
    form = ModelForm(initial=initial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\admin_tools_stats\admin.py", line 89, in __init__
    self.fields["default_multiseries_criteria"].queryset = CriteriaToStatsM2M.objects.filter(
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 147, in get_prep_lookup
    self.rhs = get_normalized_value(self.rhs, self.lhs)[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theus\python\django\venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 45, in get_normalized_value
    raise ValueError("Model instances passed to related filters must be saved.")
ValueError: Model instances passed to related filters must be saved.

**Comment by syny-pulse** [comment]
I am facing a similar challenge, @koukou777 have you been able to fix this?

**Comment by ddkasa** [comment]
Same issue here, is there a fix in the works for this? 

I don't mind contributing a PR if no one else if working on this at the moment?

**Comment by PetrDlouhy** [comment]
Hi all,

I have tried this with Django 5.0.4. and PostgreSQL and pressing Add on Dashboard stats works fine for me.
Do you use MySQL or might there be anything else specific to this issue?

@ddkasa Any help would be greatly appreciated and even narrowing down cause of this failure would be great help.

**Comment by PetrDlouhy** [comment]
Note: I am getting error `AttributeError: 'super' object has no attribute '_get_flatchoices'` with Django 5.0 which is caused by `django-multiselectfield` not yet being compatible with Django 5.0: https://github.com/goinnn/django-multiselectfield/pull/146
That is different error and can be solved by installing the version from GIT repository.

**Comment by PetrDlouhy** [comment]
I have updated the testing matrix to Django 4.2 in `master` branch.
Unfortunately there are some randomly ocuring `Column 'multiple_series_choice_id' cannot be null")` errors with MySQL (but that was the case even before this update).

The work on Django 5.0 support could be based on this PR: https://github.com/PetrDlouhy/django-admin-charts/pull/73
But the tests are failing there because of the `django-multiselectfield` and I thing we need to wait until that is fixed (with updating testing, fixes can be released sooner).

**Comment by ddkasa** [comment]
> Hi all,
> 
> I have tried this with Django 5.0.4. and PostgreSQL and pressing Add on Dashboard stats works fine for me. Do you use MySQL or might there be anything else specific to this issue?
> 
> @ddkasa Any help would be greatly appreciated and even narrowing down cause of this failure would be great help.

@PetrDlouhy I am using django 5.3 with Postgres 15.

I have tried your Django 5.0 **branch**  with the Multiselect **repository** and and it fixed the issues for me partially.

I had to comment out this line in order to get a bandaid fix working for now as it was the perpetrator:

https://github.com/PetrDlouhy/django-admin-charts/blob/f818649be0a3b49206064fd5a4689f34f60afa61/admin_tools_stats/admin.py#L89C1-L91C10?plain=1

**Comment by PetrDlouhy** [comment]
I have released version `1.3.1` with the fix for this issue. Please reopen if it doesn't fix it.
