### ISSUE TITLE
AttributeError at /admin/ 'str' object has no attribute 'get_control_form_raw'

### ISSUE THREAD

**Issue by milin** [PetrDlouhy/django-admin-charts#33]
http://localhost:8000/admin/
django - 3.1.13
AttributeError
'str' object has no attribute 'get_control_form_raw'

Exception Location: packages/admin_tools_stats/templatetags/admin_chart_tags.py, line 35, in get_control_form

Getting the following exception right after upgrading to 0.25.0 and also in the latest master. Seems like it renders the package unusable.

**Comment by PetrDlouhy** [comment]
@milin Can you please add full error stack. Are you using `admin-tools`? Does this happen on the index of admin?

**Comment by PetrDlouhy** [comment]
@milin It seems, that the problem could be somewhere in your `dashboard.py` configuration. Can you please post also the section with charts initialization from there?

**Comment by milin** [comment]
> Are you using django-admin-tools?

No 
> Does this happen on the index of admin?

Yes

> It seems, that the problem could be somewhere in your dashboard.py configuration.

I am not sure what is `dashboard.py` config. I don't think I have one.

For the time being, I reverted to an older commit from master, to make things work. I will bump the version to 0.25.0 again, and post the entire stack, it may take some time though.

**Comment by PetrDlouhy** [comment]
@milin Hi, I have found the problem. I didn't test it on plain admin.
Now it should work in `0.25.1`. Please test and reopen if you see this problem, or open new issue, if you bump into something else.

Thank you for noticing this issue.
